### ISSUE TITLE
Specify Certificate for Web Interface

### ISSUE THREAD

**Issue by jseiser** [kbrebanov/ansible-openvpn_as#6]
I was wondering if you had found a way to pass in a cert, chain and private key file to use for the web interface?  If you manually set it in the UI, its overwrote by the role when executed.

**Comment by jseiser** [comment]
I have this working, not sure how to clean up my branch enough to submit the PR though.

as.conf.j2
```
{% if openvpn_as_custom_cert %}
cs.ca_bundle={{ openvpn_as_ca_bundle }}
cs.priv_key={{ openvpn_as_ca_priv_key }}
cs.cert={{ openvpn_as_ca_cert }}
{% else %}
cs.ca_bundle=~/web-ssl/ca.crt
cs.priv_key=~/web-ssl/server.key
cs.cert=~/web-ssl/server.crt
{% endif %}
```

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
